<#
Author: Eric Sobkowicz
Created: December 21, 2017
Last Updated By: Eric Sobkowicz
Last Updated: December 27, 2017

Purpose: 
    To properly convert a given user mailbox to a shared mailbox by migrating it to the on prem exchange server, converting it, then migrating it back to O365

Requirements: 
    Hybrid Exchange environment, RSAT tools installed on the system running the script.

Variables:
    $ExchangeServer - The computer name of the Exchange server
    $SyncServer - The computer name of the Azure AD sync server
    $ADDomain - The local AD domain
    $EmailDomain - The local email domain
    $O365Domain - The .onmicrosoft.com domain for your O365 tennant
    $MigrationEndpoint - The DNS address of your O365 Migration Endpoint, this can be easily viewed in the O365 GUI by doing a manual migration
    $Database - Local On Prem Exchange Database name

Notes:
    All computer names should be the short name, not the FQDN, if the FQDN is needed they will be combined in the script with the domain name in the $ADDomain variable.
#>
# Treats every error as a terminating error, supresses warnings generated by connecting to O365 commands etc.
$ErrorActionPreference = "Stop"
$WarningPreference = "SilentlyContinue"

# Variables
$ExchangeServer = "ExchangeServerName"
$SyncServer = "SyncserverName"
$ADDomain = "ADDomainName"
$EmailDomain = "Local Email Domain"
$O365Domain = "client.onmicrosoft.com"
$MigrationEndpoint = "ExternalMigrationEndpointFQDN"
$Database = "Exchange OnPrem Database Name"

function main
{
# Creates some blank space at the top of the console window so that the progress bars futher in don't hide the various text outputs.
Write-Host "






"

# Prompts user for credentials
$Cred = Get-Credential -Message "Please enter the Office 365 credentials (username@domain)"
$LocalCred = Get-Credential -Message "Please enter the Domain Admin credentials (username@domain)"

# Asks the admin for the account name and checks to see if it exists, if it does not the script writes an error message and ends.
$Alias = Read-Host "Please enter the account name"
try
	{
	Get-ADUser $Alias | Out-Null
	}
catch
	{
	Write-Host "The user you have entered does not exist, please ensure you have the correct username and re-run the script." -ForegroundColor Red
	Exit
	}
Write-Host "The user is valid." -ForegroundColor Green

# Connect to O365 and check the current mailbox type, ask user if they want to continue.
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $Cred -Authentication Basic -AllowRedirection
Import-PSSession $Session | Out-Null
While ($Answer -ne "Y")
    {
    Write-Host "The current Mailbox Type for the user $Alias is $((Get-Mailbox -Identity $Alias).RecipientTypeDetails)" -ForegroundColor DarkYellow
    $Answer = Read-Host "Would you like to convert the mailbox to a shared mailbox? (Y/N)"
    If ($Answer -eq "N")
        {
        Write-Host "You have entered N, exiting script, no changes have been made." -ForegroundColor Red
        Remove-PSSession $Session | Out-Null
        Exit
        }
    If ($Answer -ne "Y")
        {
        Write-Host "You have entered an invalid selection." -ForegroundColor Yellow
        }
    }
Remove-PSSession $Session | Out-Null

# Call the Migrate-Mailbox function to migrate the mailbox to on prem, deletes the migration batch once done.
Migrate-Mailbox -Cred $Cred -LocalCred $LocalCred -Alias $Alias -MigrationEndpoint $MigrationEndpoint -O365Domain $O365Domain -Direction "To OnPrem" -EmailDomain $EmailDomain -Database $Database

# Creates a PS session to the local exchange server, converts the mailbox to a shared mailbox.
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri "http://$ExchangeServer.$ADDomain/PowerShell/" -Authentication Kerberos -Credential $LocalCred
Import-PSSession $Session | Out-Null
Write-Host "Converting mailbox to shared mailbox"
try
    {
    Set-Mailbox -Identity $Alias -Type Shared | Out-Null
    }
catch
    {
    Write-Host "Failed to convert mailbox to shared, exiting script." -ForegroundColor Red
    Remove-PSSession $Session | Out-Null
    Exit
    }
Remove-PSSession $Session | Out-Null

# Waits 5 minutes for AD replication to take place, then kicks off the sync to O365, then waits for 10 Minutes for it to complete and replicate between the pods.
Create-ProgressBar -Time 300 -Message "Waiting for AD Replication"
Invoke-Command {Start-ADSyncSyncCycle -PolicyType Delta} -computer "$SyncServer.$ADDomain"
Create-ProgressBar -Time 600 -Message "Waiting for O365 Replication"

# Call the Migrate-Mailbox function to migrate the mailbox back to the cloud, deletes the migration batch once done.
Migrate-Mailbox -Cred $Cred -LocalCred $LocalCred -Alias $Alias -MigrationEndpoint $MigrationEndpoint -O365Domain $O365Domain -Direction "To O365"

# Call the Remove-Licenses function to remove all licenses from the mailbox as they are no longer needed.
Remove-Licenses -Cred $Cred -UPN "$Alias@$EmailDomain"

# Connects to O365, verifies the mailbox type and outputs final success message.
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $Cred -Authentication Basic -AllowRedirection
Import-PSSession $Session | Out-Null
Write-Host "The script has completed successfully, the mailbox is now type: $((Get-Mailbox -Identity $Alias).RecipientTypeDetails) " -ForegroundColor Green
Remove-PSSession $Session | Out-Null
}

<#
Purpose: 
    This function waits the specified $time in seconds and creates a progress bar that shows the time remaining, percent complete, and message set with $Message

Requirements:
    None

Variables:
    $Time - the ammount of time to wait in seconds
    $Message - The message to display on the progress bar

#>
Function Create-ProgressBar ($Time, $Message)
{
For($I=$Time; $I -gt 0; $I--)
		{
		Write-Progress -Activity "$Message" -Status "Progress" -SecondsRemaining $I -PercentComplete (($Time-$I)/$Time*100)
		Start-Sleep -s 1
		}
}

<#
Purpose: 
    This function migrates the specified mailbox to O365, waits until the migration done before proceeding. During the migration a status bar will be displayed showing the current
    status detail with the percent complete represented on the progress bar.  Every 5 min the user will be given the current status of the migration and asked if they wish to continue
    waiting for the migration, the script will exit if the user enters N.  This version can migrate to or from O365 depending on the $Direction variable.

Requirements: 
    O365 powershell installed on the system running the script

Variables:
    $Cred - The O365 credentials as a PSCredential object
    $LocalCred - The Credentials for the local domain with permissions to perform the migration on the local exchange server.
    $Alias - The username of the account to be migrated
    $MigrationEndpoint - The external FQDN of the migration endpoint
    $O365Domain - The .onmicrosoft.com domain of the tennant
    $Direction - Specifies whether the migration is going to O365 or to On Prem.  Accepted values "To O365" and "To OnPrem"
    $EmailDomain - The local email domain, only needed if migrating to on prem
    $Database - The Database name of the local Exchange database, only needed if migrating to on prem.
#>

Function Migrate-Mailbox ($Cred, $LocalCred, $Alias, $MigrationEndpoint, $O365Domain, $Direction, $EmailDomain, $Database)
{
# Connect to O365
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $Cred -Authentication Basic -AllowRedirection
Import-PSSession $Session | Out-Null

# Check the direction variable, perform the appropriate move request command to move from O365 to on prem or from on prem to O365, exit with an error if the command throws an error.
if ($Direction -eq "To O365")
    {
    try
	    {
	    New-MoveRequest -Identity $Alias -Remote -RemoteHostName $MigrationEndpoint -TargetDeliveryDomain $O365Domain -RemoteCredential $LocalCred | Out-Null
	    }
    catch
	    {
	    Write-Host "An error occured creating the mailbox migration." -ForegroundColor Red
	    Exit
	    }
    }
elseif ($Direction -eq "To OnPrem")
    {
    try
	    {
	    New-MoveRequest -Identity $Alias -Outbound -RemoteTargetDatabase $Database -RemoteHostName $MigrationEndpoint -TargetDeliveryDomain $EmailDomain -RemoteCredential $LocalCred | Out-Null
	    }
    catch
	    {
	    Write-Host "An error occured creating the mailbox migration." -ForegroundColor Red
	    Exit
	    }
    }
# Throw an error and exit the script if the direction is not set correctly.
else
    {
    Write-Host "The value $Direction for the `$Direction variable is an invalid entry, exiting script" -ForegroundColor Red
    Exit
    }
# Show a progress bar while the migration is being done, check with the user every 5 min if the migration is still ongoing to see if they want to wait or exit the script.
$MoveRequestStatistics = Get-MoveRequest $Alias | Get-MoveRequestStatistics
While ($MoveRequestStatistics.PercentComplete -ne 100)
    {
    $MoveRequestStatistics = Get-MoveRequest $Alias | Get-MoveRequestStatistics
    Write-Progress -Activity "Waiting for Mailbox Migration" -Status $MoveRequestStatistics.StatusDetail.Value -PercentComplete $MoveRequestStatistics.PercentComplete
    Start-Sleep -s 4
    $i ++
    If ($i%60 -eq 0)
        {
        Write-Host "The current status of the migration is:"
        Get-MoveRequest $Alias | Get-MoveRequestStatistics | Format-Table DisplayName, StatusDetail, TotalMailboxSize, TotalArchiveSize, PercentComplete
        $Answer = Read-Host "Would you like to wait another 5min for the Migration to complete? (Y/N)"
        If ($Answer -eq "N")
            {
            Write-Host "You have selected not to wait, the script will now exit, you will need to manually complete the migration and any other pending tasks" -ForegroundColor Red
            Exit
            }
        }
    }
# Output the final status of the migration once it completes, delete the migration batch, close the connection to O365 and return from the function.
Write-Host "The migration has completed, here is the final status of the migration:" -ForegroundColor Green
Get-MoveRequest $Alias | Get-MoveRequestStatistics | Format-Table DisplayName, StatusDetail, TotalMailboxSize, TotalArchiveSize, PercentComplete
Get-MoveRequest -Identity $Alias | Remove-MoveRequest -Confirm:$false | Out-Null

Remove-PSSession $Session | Out-Null
}

<#
Purpose: 
    Takes a given user and removes all licenses associated with them.

Requirements: 
    Need to have the MSOnline module installed on the system running the script.

Variables:
    $Cred - O365 admin credentials as a PS credential object
    $UPN - the User Principal Name of the user to remove the licenses from in format username@domain
#>

function Remove-Licenses ($Cred, $UPN)
{
# Import the MSOnline module and connect to Azure AD
Import-Module MSOnline | Out-Null
Connect-MsolService -Credential $Cred

# List the licenses applied to the user.
Write-Host "The current licensing applied to the selected user is as follows:" -ForegroundColor Magenta
Get-MsolUser -UserPrincipalName $UPN | Format-Table UserPrincipalName, DisplayName, IsLicensed, Licenses

# Asks the end user if they want to remove all the licenses, if they enter an incorrect value it throws a warning and asks again, if they enter N then it exits the script, continues on Y.
While ($Choice -ne "Y")
    {
    $Choice = Read-Host "Would you like to remove all listed licenses (Y/N): "
    If ($Choice -eq "N")
        {
        Write-Host "You have chosen to not remove the licenses from the user $UPN, exiting script."-ForegroundColor Red
        Exit
        }
    If ($Choice -ne "Y")
        {
        Write-Host "You have entered an invalid entry, please enter Y for Yes or N for No." -ForegroundColor Red
        }
}

# Pulls a list of licenses attached to the user and removes all of them.
try
    {
    (Get-MsolUser -UserPrincipalName $UPN).licenses.AccountSkuId | ForEach-Object{Set-MsolUserLicense -UserPrincipalName $upn -RemoveLicenses $_}
    }
catch
    {
    Write-Host "A problem occured during the removal of the licenses, exiting script." -ForegroundColor Red
    Exit
    }

# Lets the user know that the removal is finished and ouputs the current licensing status of the mailbox.
Write-Host "The license removal was successful, here is the current license status of the maibox:" -ForegroundColor Green
Get-MsolUser -UserPrincipalName $UPN | Format-Table UserPrincipalName, DisplayName, IsLicensed, Licenses
}

# Runs the Main function
# Putting the main code within a function and calling it at the end of the script allows for the main code to be at the top of the script and all other functions below it
Main